name: Lint TRR on Push to Reports
run-name: Linting branch ${{ github.ref_name }}
on:
   push:
     branches:
       - 'reports/**'
jobs:
  run_linter: 
    runs-on: ubuntu-latest
    steps:
    
     - name: Check out repo
       uses: actions/checkout@v4

     - name: Setup Go environment
       uses: actions/setup-go@v5.5.0
       with:
         go-version: '1.21'
         
     - name: Install dependencies
       run: go get github.com/yuin/goldmark 
       
     - name: Run linter
       run: go run tools/trrlint/main.go
