name: Branch Validation on PR
run-name: Validating branch ${{ github.head_ref }} on PR creation/modification
on: 
   pull_request:
      types: [opened, synchronize, reopened]
jobs: 
   validate-branch:
      runs-on: ubuntu-latest
      steps:

        # Verify that the branch has one of the valid prefixes (reports, tasks, docs, tools). Fail for anything else.
        - name: Check Branch Name
          uses: actions/github-script@v7
          with:
            script: |
              const branchName = context.payload.pull_request.head.ref;
              const regex = /^reports|tasks|docs|tools\//;
              if (!regex.test(branchName)) {
                 core.setFailed('Branch does not follow required naming convention. Please refer to the contribution guide.');
              } else {
                 console.log('Branch name matches required format.');
              }
              
        # Verify that a TRR update branch contains a trr0000 folder (the name specified in the contribution guide for a new TRR)
        # Failure to use the right folder name will cause a TRR number assignment failure later.
        - if: ${{ startsWith(github.head_ref, 'reports/') && !startsWith(github.head_ref, 'reports/update/') }} 
          name: Verify new TRR folder
          run: |
             if [ -d "reports/trr0000" ]; then
                echo "Validated that trr0000 folder exists for new TRR branch."
                exit 0
             else
                echo "Branch is a new TRR branch but does not have a reports/trr0000 folder. Please refer to style guide."
                exit 1
             fi

        # Verify that a TRR update branch does NOT have a trr0000 folder, which should only be used for net new TRRs.     
        - if: ${{ startsWith(github.head_ref, 'reports/update/') }} 
          name: Verify no new TRR folder for TRR update branch
          run: |
             if [ ! -d "reports/trr0000" ]; then
                echo "Update branch: validated that there is no new TRR folder."
                exit 0
             else
                echo "Branch is a TRR update branch but has a reports/trr0000 folder. Update branches should not have new TRRs. Please refer to the contribution guide."
                exit 1
             fi

        # Make sure that the branch is ONLY changing files appropriate to its type
        # e.g. reports branches only modify TRR files, docs branches only modify docs, etc.
        - name: Get list of files changed in PR
          uses: tj-actions/changed-files@6cb76d07bee4c9772c6882c06c37837bf82a04d3 # v46
          id: changed-files
          
        - name: Validate branch only changes files in appropriate folder 2
          uses: actions/github-script@v7
          with:
            script: |
               const branchName = context.payload.pull_request.head.ref;
               const changedFiles = "${{ steps.changed-files.outputs.all_changed_files }}".split(" ");
               const folder = branchName.split("/")[0];
               console.log(changedFiles);
               console.log(folder);
               if (folder == "tasks") {
                 // no limitation on files edited by task PRs
                 return true;
               }
               changedFiles.forEach((file) => {
                 if (!file.startsWith(folder)) {
                   core.setFailed('Branch does not follow required naming convention. Each branch should only edit files in its respective folder. Please refer to the contribution guide.');
                 }
               });
